export const COLORS = {
  primaryColor: '#FFF',
  secondaryColor: '#000',
  portColor: '#0EC9F2',
  vision: '#46DABE',
  // serviceColor: '#0E52F2',
  serviceColor: '#46DABE',
  textColor: '#5A5A5A',
  contactBackground: '#000371',
  cardBackground : "#E9EEF4",
  globalCardBackground : "#F2F7FC",
  headerBackground : "#111F40",
  pointerBackground : '#5F62E9',
  footerBackground : "#111",
  footerTextColor : "#ccc",
  background : '#F9F9F9',
  accordian_background : '#F5F5F5',
  arrow_background : '#F3F3F3',
  news_title : '#121212',
  backgroundColor:"#EFF6FF",
};
